### ISSUE TITLE
Add authentication via Steam

### ISSUE THREAD

**Issue by cvan** [mozilla/galaxy-api#270]

**Comment by cvan** [comment]
Previously this was Persona, then tentatively Firefox Accounts, then tentatively Twitter. Now let's do [Steam](http://steamcommunity.com/dev) (which offers an OpenID identity solution).

**Comment by AdrianGaudebert** [comment]
Any reason to choose Steam particularly? And why do we drop FxAccounts?

**Comment by cvan** [comment]
> Any reason to choose Steam particularly?

audience is already there. it allows "friends" out of the box.

> And why do we drop FxAccounts?

I want to be able to provide a client-side library ([`galaxy.js`](https://github.com/mozilla/galaxy.js))

so inside a game, you would call [`galaxy.authenticate()`](http://mozilla.github.io/galaxy.js/docs/galaxy.js.html#authenticate).

the FxA folks told me that I wouldn't be able to do this. integrating FxA in Marketplace was a non-trivial task, because it's not meant for "app stores"/"marketplaces."

the Marketplace is the first third-party consumer of FxA, and as it's not battle-tested yet, I don't want to integrate it to only yank it out. a year ago, we added Persona only to have Persona deprecated now.

so yeah, in an ideal world, FxA would be simply integratabtle. when it's ready, and it has *proven value*, let's use it.

**Comment by AdrianGaudebert** [comment]
Fair enough! :) So we won't build "social" features like friends anymore and instead use what Steam can offer? That sounds good to me if we want to move fast.

**Comment by cvan** [comment]
exactly. at least for the next month. this work will be demoed at GDC, so trying to move fast.
